language: python
cache: pip
python:
# temporary broken
#  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy"
# temporary broken
#  - "pypy3"
install:
  - pip install codecov
  - pip install -r requirements.txt
  - pip install -e .
script:
  - sh runtests.sh
